name: CI

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  create_commit_change_log:
    runs-on: ubuntu-latest
    steps:
  
    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0

    - name: Create_commit_change_log_file
      uses: TriPSs/conventional-changelog-action@v1.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Debuggging with tmate
      uses: GitHub30/action-tmate@master2