name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: TriPSs/conventional-changelog-action@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output-file: 'CHANGELOG.md'
          changelog-release-count: 5

