name: CI

on:
  push:
    # branches to consider in the event; optional, defaults to all
    # branches:
    #  - refs/heads/master 

jobs:
  create_commit_change_log:
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout
      uses: actions/checkout@v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN_ACTION  }}

    - name: Create_commit_change_log_file
      uses: TriPSs/conventional-changelog-action@v1.3.0
     with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
       tag-prefix: ''
       changelog-release-count: 5


