name: Commit Changelog

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:      
      # Update Commit file
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output-file: 'CHANGELOG.md'
          changelog-release-count: 5
