name: CI

on:
  push:
    # branches to consider in the event; optional, defaults to all
    # branches:
    #  - refs/heads/master 

jobs:
  create_commit_change_log:
    runs-on: ubuntu-latest
    steps:
   
    - name: Checkout
      uses: actions/checkout@v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN_ACTION  }}

    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v2.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        tag-prefix: 'v'
        changelog-release-count: 0

    - name: Read package.json node version
      uses: culshaw/read-package-node-version-actions@v2.0.0
      id: package-node-version
      with:
        path: package.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - uses: microsoft/variable-substitution@v1 
      with:
        files: 'GrampsView.Android\Properties\AndroidManifest.xml'
      env:
        Var1: "versionCode"
        Var2.key1: steps.package-node-version.outputs.version
        SECRET: ${{ secrets.GITHUB_TOKEN }}
        
#    - name: git Actions
#      uses: srt32/git-actions@v0.0.3
#      with:
 #       args: git log --pretty --oneline --decorate -n 10 --format=medium > GrampsView/CHANGELOG.md


#    - uses: stefanzweifel/git-auto-commit-action@v4.1.2
#      with:
 #       commit_message: Update changelog
#
#        # Optional glob pattern of files which should be added to the commit
#        file_pattern: GrampsView/*.md
#
#        # Optional commit user and author settings
#        commit_user_name: phandcock
#        commit_user_email: phandcockregister@gmail.com
#        commit_author: phandcock <phandcockregister@gmail.com>
    

#    - name: Generate Auto Changelog
#      uses: ahmadawais/action-auto-changelog@master
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}

#    - name: Generate changelog
#      uses: charmixer/auto-changelog-action@v1
#      with:
#        token: ${{ secrets.GITHUB_TOKEN_ACTION }}

#    - name: Commit files
#      env:
#         CI_USER: ${{ secrets.YOUR_GITHUB_USER }}
##         CI_EMAIL: ${{ secrets.YOUR_GITHUB_EMAIL }}
#      run: |
#          git config --local user.email "phandcockregister@gmail.com"
#          git config --local user.name "phandcock"
#          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo ::set-env name=push::1 || echo "No changes to CHANGELOG.md"
